name: Checks

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install yamllint
        run: make install-yamllint

      - name: run yamllint
        run: yamllint . -f github
